### ISSUE TITLE
Notification Trigger

### ISSUE THREAD

**Issue by flyinstefan** [Klettner/MMM-StopwatchTimer#1]
Hi,

could you please post an example of a valid notification post. I could not make it work.
i tried:
`curl -H "Content-Type: application/json" -X POST -d '{"notification":"START_TIMER", "payload": {"seconds": "120"}}' http://localhost:8080/kalliope`
and variations.
The notification shows up on the Magic Mirror in my notification reader, but does not start the timer.

Thanks a lot
Stefan

**Comment by Klettner** [comment]
Hi Stefan,

to communicate with the Magic Mirror I'm using the api of [MMM-Remote-Controle](https://github.com/Jopyth/MMM-Remote-Control). Depending on the version of the api you are using, there are different ways to start a notification.
* With the recent api and the use of an api key, you can start a timer this way:
``curl -H @{'Authorization' = 'apiKey <your_api_key>'} http://<your_ip-address>:8080/api/notification/START_TIMER/120 `` (you need to replace \<your_api_key\> and \<your_ip-address\> with values applicable to your Mirror).
* With the deprecated api (which should still work) you can use:
``curl 'http://<your_ip-address>:8080/remote?action=NOTIFICATION&notification=START_TIMER&payload=120'``  

I hope that helps. Have fun with the module :)
Manuel
