### ISSUE TITLE
Confusion over how to submit payload in notification

### ISSUE THREAD

**Issue by apag104** [Klettner/MMM-StopwatchTimer#3]
This is a beginner question but I cannot figure out how to format the notification START_TIMER to include the payload. Do I format as x.seconds/ x.minutes? is this a noticiation sent with START_TIMER notification?

**Comment by Klettner** [comment]
Hi,   
to start a timer for lets say 12 seconds the notification would be: ``START_TIMER`` and the payload: ``12``.   
If you are using for example the [MM-Remote](https://github.com/Klettner/MM-Remote) App to send you notification you can do it like this: 
![grafik](https://user-images.githubusercontent.com/61590348/118113082-20daeb00-b3e6-11eb-984e-75432a1bd1ca.png)  
If you are using [MMM-Remote-Control](https://github.com/Jopyth/MMM-Remote-Control) to send the notification you can follow the instructions of [this issue](https://github.com/Klettner/MMM-StopwatchTimer/issues/1)
